# Generated by Django 3.1.7 on 2021-04-08 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('state_level', 'State Level'), ('district_level', 'District Level')], max_length=20)),
                ('tournament', models.CharField(choices=[('football', 'Football'), ('cricket', 'Cricket'), ('volley_ball', 'Volley Ball'), ('hockey', 'Hockey'), ('badminton', 'Badminton'), ('basket_ball', 'Basket Ball')], max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('venue', models.CharField(max_length=60)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Winners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.CharField(max_length=100)),
                ('silver', models.CharField(max_length=100)),
                ('bronze', models.CharField(max_length=100)),
                ('winners_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners_for', to='users.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Participated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('player_1', models.CharField(max_length=100)),
                ('player_2', models.CharField(max_length=100)),
                ('player_3', models.CharField(max_length=100)),
                ('player_4', models.CharField(max_length=100)),
                ('player_5', models.CharField(max_length=100)),
                ('player_6', models.CharField(max_length=100)),
                ('player_7', models.CharField(max_length=100)),
                ('player_8', models.CharField(max_length=100)),
                ('player_9', models.CharField(max_length=100)),
                ('player_10', models.CharField(max_length=100)),
                ('player_11', models.CharField(max_length=100)),
                ('participate_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participate_for', to='users.tournament')),
            ],
        ),
    ]
