# Generated by Django 3.1.7 on 2021-03-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210320_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
