# Generated by Django 3.1.7 on 2021-03-30 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210321_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.CharField(max_length=100)),
                ('silver', models.CharField(max_length=100)),
                ('bronze', models.CharField(max_length=100)),
                ('winners_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners_for', to='users.tournament')),
            ],
        ),
    ]
